# logging
logging:
  level:
    '[com.springboot.javarestapi]': TRACE

# configuration
app:
  timezone: Asia/Jakarta
credential:
  APIkey: ${SECRET_KEY}

# database source
spring:
  datasource:
    url: jdbc:postgresql://db.tjkpmbdcypziwibsrtso.supabase.co:5432/postgres?user=postgres&password=Mu1V2tQMvc2qrzBW
    username: postgresql
    password: Mu1V2tQMvc2qrzBW
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# binding text example for end point get("/")
welcome:
    text: Welcome to desta app

# identify server port running on default environment
server:
  port: 9001

######## identify server for dev environment ########
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://db.tjkpmbdcypziwibsrtso.supabase.co:5432/postgres?user=postgres&password=Mu1V2tQMvc2qrzBW
    username: postgresql
    password: Mu1V2tQMvc2qrzBW
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# binding text example for end point get("/")
welcome:
    text: Welcome to desta development area

# identify server port running on local for dev environment
server:
  port: 9000

######## identify server for prod environment ########
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db.tjkpmbdcypziwibsrtso.supabase.co:5432/postgres?user=postgres&password=Mu1V2tQMvc2qrzBW
    username: postgresql
    password: Mu1V2tQMvc2qrzBW
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# binding text example for end point get("/")
welcome:
    text: Welcome to desta prod area

# identify server port running on local for prod environment
server:
  port: 8000

